version: '3.8'

networks:
  flask_network:
    driver: bridge

services:
  flask1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask1_container
    networks:
      - flask_network
    expose:
      - "5000"

  flask2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask2_container
    networks:
      - flask_network
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - flask_network