version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always