version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: votes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voting_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./worker
    container_name: worker_container
    networks:
      - voting_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  voting_network:
    driver: bridge